app/media/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileRequired
from wtforms import StringField, FileField, TextAreaField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Length
from app.models import User, Video, Photo



class EmptyForm(FlaskForm):
    submit = SubmitField("Submit")


class CommentForm(FlaskForm):
    comment  = TextAreaField("Comment...", validators=[DataRequired(), Length(min=1, max=140)])
    submit = SubmitField("Submit")


class UploadVideoForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    description = TextAreaField("Description", validators=[DataRequired(), Length(min=1, max=140)], default="None.")
    upload = FileField("Video File", validators=[FileRequired()])
    submit = SubmitField("Upload")

    def validate_title(self, title):
        video = Video.query.filter_by(title=title.data).first()
        if video is not None:
            raise ValidationError("Title already taken.")


class UploadPhotoForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    upload = FileField("Image File", validators=[FileRequired()])
    submit = SubmitField("Upload")

    def validate_title(self, title):
        photo = Photo.query.filter_by(title=title.data).first()
        if photo is not None:
            raise ValidationError("Title already taken.")

app/media/__init__.py
from flask import Blueprint


bp = Blueprint('media', __name__)


from app.media import routes

app/media/routes.py
import os
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, send_from_directory, jsonify, current_app
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename
from app import db
from app.media.forms import UploadVideoForm, CommentForm, UploadPhotoForm, EmptyForm
from app.models import User, Video, Post, Comment, Photo
from app.media import bp


def allowed_image_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in current_app.config['IMAGE_EXTENSIONS']


def allowed_video_file(filename):
    return '.' in filename and filename.rsplit(".", 1)[1].lower() in current_app.config['VIDEO_EXTENSIONS']


@bp.route("/dev_channel", methods=['GET', 'POST'])
def dev_channel():
    #form = EmptyForm()
    page = request.args.get('page', 1, type=int)
    videos = Video.query.order_by(Video.timestamp.desc()).paginate(
        page, current_app.config['MEDIA_PER_PAGE'], False
    )
    next_url = url_for('media.dev_channel', page=videos.next_num) if videos.has_next else None
    prev_url = url_for('media.dev_channel', page=videos.prev_num) if videos.has_prev else None

    return render_template('media/dev_channel.html', title="Dev Channel", videos=videos.items, next_url=next_url, prev_url=prev_url)


@bp.route('/video/<video_id>', methods=['GET', 'POST'])
def video(video_id):
    video = Video.query.filter_by(id=video_id).first_or_404()
    all_vids = Video.query.order_by(Video.timestamp.desc())
    form = CommentForm()
    if form.validate_on_submit():
        if current_user.is_anonymous:
            flash("Only users can comment.")
            return redirect(url_for('media.video', video_id=video_id))
            
        comment = Comment(body=form.comment.data, video=video, author=current_user)
        db.session.add(comment)
        db.session.commit()
        flash("Comment submitted.")
        return redirect(url_for("media.video", video_id=video_id))
    
    page = request.args.get('page', 1, type=int)
    comments = Comment.query.filter_by(video=video).order_by(Comment.timestamp.desc()).paginate(
        page, current_app.config['ITEMS_PER_PAGE'], False
    )
    next_url = url_for('media.video', video_id=video_id, page=comments.next_num) if comments.has_next else None
    prev_url = url_for('media.video', video_id=video_id, page=comments.prev_num) if comments.has_prev else None

    return render_template('media/video.html', title=video.title, video=video, comments=comments.items, form=form, next_url=next_url, prev_url=prev_url, all_vids=all_vids)


@bp.route('/watch/<video_id>')
def watch(video_id):
    video = Video.query.filter_by(id=video_id).first_or_404()

    return send_from_directory(os.path.join(current_app.config['UPLOAD_FOLDER'], 'videos'), video.filename)



@bp.route("/upload_video", methods=['GET', 'POST'])
@login_required
def upload_video():
    if current_user.email not in current_app.config['ADMINS']:
        flash("You are not authorized to access this page.")
        return redirect(url_for('main.index'))

    form = UploadVideoForm()
    if form.validate_on_submit():
        f = form.upload.data
        
        if not allowed_video_file(f.filename):
            flash("Invalid file type")
            return redirect(url_for('media.upload_video'))

        filename = secure_filename(f.filename)
        f.save(os.path.join(current_app.config['UPLOAD_FOLDER'], 'videos', filename))
        video = Video(title=form.title.data, description=form.description.data, filename=filename)

        db.session.add(video)
        db.session.commit()
        flash("Video uploaded successfully.")
        return redirect(url_for('media.video', video_id=video.id))

    return render_template('media/upload_video.html', title="Upload Video", form=form)


@bp.route("/upload_photo", methods=['GET', 'POST'])
@login_required
def upload_photo():
    if current_user.email not in current_app.config['ADMINS']:
        flash("You are not authorized to access this page.")
        return redirect(url_for('main.index'))

    form = UploadPhotoForm()
    if form.validate_on_submit():
        f = form.upload.data

        if not allowed_image_file(f.filename):
            flash("Invalid file type")
            return redirect(url_for("media.upload_photo"))

        filename = secure_filename(f.filename)
        f.save(os.path.join(current_app.config['UPLOAD_FOLDER'], 'photos', filename))
        photo = Photo(title=form.title.data, filename=filename)

        db.session.add(photo)
        db.session.commit()

        flash("Photo uploaded")
        return redirect(url_for('media.gallery'))

    return render_template('media/upload_photo.html', title="Upload Photo", form=form)


@bp.route('/gallery')
def gallery():
    page = request.args.get('page', 1, type=int)
    photos = Photo.query.order_by(Photo.timestamp.desc()).paginate(
        page, current_app.config['MEDIA_PER_PAGE'], False
    )
    next_url = url_for('media.gallery', page=photos.next_num) if photos.has_next else None
    prev_url = url_for('media.gallery', page=photos.prev_num) if photos.has_prev else None

    return render_template('media/gallery.html', title="Gallery", photos=photos.items, next_url=next_url, prev_url=prev_url)

    
    
@bp.route('/image/<photo_id>')
def image(photo_id):
    photo = Photo.query.filter_by(id=photo_id).first_or_404()
    return send_from_directory(os.path.join(current_app.config['UPLOAD_FOLDER'], 'photos'), photo.filename)

    

app/templates/media/_video.html
<table class="table table-hover bg-orange">
	<tr>
		<td width="320px">
			<video width="320" height="240" controls>
				<source src="{{ url_for('media.watch', video_id=video.id) }}">
			Cannot play video
			</video>
		</td>
		<td>
			<a href="{{ url_for('media.video', video_id=video.id) }}"><h3>{{ video.title }}</h3></a>
			<p class="text-muted">{{ video.description }}
		</td>
	</tr>
</table> 

app/templates/media/dev_channel.html
{% extends "base.html" %}


{% block app_content %}
<h1>Dev Channel</h1>
<div class="container bg-3">
{% for video in videos %}
	{% include 'media/_video.html' %}
{% endfor %}
</div>
<nav aria-label="...">
	<ul class="pager">
		<li class="previous{% if not prev_url %} disabled{% endif %}">
			<a href="{{ prev_url or '#' }}">
				<span aria-hidden="true">&larr;</span> Newer videos
			</a>
		</li>
		<li class="next{% if not next_url %} disabled{% endif %}">
			<a href="{{ next_url or '#' }}">
				Older posts <span aria-hidden="true">&rarr;</span>
			</a>
		</li>
	</ul>
</nav>
{% endblock %}

app/templates/media/gallery.html
{% extends "base.html" %}

{% block app_content %}
<div class="jumbotron">
	<div class="container text-center">
		<h1>The Gallery</h1>
		<p>A collection of images capturing the life of an independent developer.</p>
	</div>
</div>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
	<div class="carousel-inner">
		{% for photo in photos %}
			<div class="item">
				<img src="{{ url_for('media.image', photo_id=photo.id) }}" alt="{{ photo.title }}">
			</div>
		{% endfor %}
	</div>
	<a class="left carousel-control" href="#myCarousel" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="right carousel-control" href="#myCarousel" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right"></span>
		<span class="sr-only">Next</span>
	</a>
</div>

	
{% endblock %}

app/templates/media/upload_photo.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<h1>Upload Photo</h1>
<div class="row bg-orange">
	<div class="col-md-8">
		{{ wtf.quick_form(form) }}
	</div>
</div>
{% endblock %}

app/templates/media/upload_video.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}


{% block app_content %}
<h1>Upload Video</h1>
<div class="row bg-orange">
	<div class="col-md-8">
		{{ wtf.quick_form(form) }}
	</div>
</div>
{% endblock %}

app/templates/media/video.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<div class="container-fluid text-center">
	<div class="row-content">
		<div class="col-sm-2 sidenav bg-orange">
			{% for vid in all_vids %}
			<p><a href="{{ url_for('media.video', video_id=vid.id) }}">{{ vid.title }}</a></p>
			{% endfor %}
		</div>
		<div class="col-sm-8">
			{% include 'media/_video.html' %}
			<hr>
			{{ wtf.quick_form(form) }}
			<hr>
				{% for post in comments %}
					{% include '_post.html' %}
				{% endfor %}
		</div>
		<div class="col-sm-2 sidenav bg-orange">
			<div class="well">
				<p>ADS</p>
			</div>
			<div class="well">
				<p>ADS</p>
			</div>
		</div>
	</div>
</div>
<nav aria-label="...">
	<ul class="pager">
		<li class="previous{% if not prev_url %} disabled{% endif %}">
			<a href="{{ prev_url or '#' }}">
				<span aria-hidden="true">&larr;</span> Newer comments
			</a>
		</li>
		<li class="next{% if not next_url %} disabled{% endif %}">
			<a href="{{ next_url or '#' }}">
				Older comments <span aria-hidden="true">&rarr;</span> 
			</a>
		</li>
	</ul>
</nav>	
		
{% endblock %}